spring:
  application:
    name: backend
  datasource:
    username: ${POSTGRES_USER_PROD}
    password: ${POSTGRES_PASSWORD_PROD}
    url: jdbc:postgresql://dpg-cqe16q1u0jms73936pq0-a.ohio-postgres.render.com/accesskey_jfzv
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  flyway:
    baseline-on-migrate: true

secret-key: ${JWT_SECRET}
jwt-token-expiration: ${EXPIRATION}
